// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
/// SHA1: 6E:F2:F6:9D:A0:65:BB:4B:BC:4F:66:C0:BE:74:E9:38:06:18:0A:0F
///
/// Example:
/// ```dart
/// import 'package:firebase_core/firebase_core.dart'
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlwdKrhJSQUPvszY_JCfJx2ybYQ1eS9G0',
    appId: '1:303738632755:web:ab75feebad3593dbbb4146',
    messagingSenderId: '303738632755',
    projectId: 'my-flutter-sa-menu',
    authDomain: 'my-flutter-sa-menu.firebaseapp.com',
    storageBucket: 'my-flutter-sa-menu.firebasestorage.app',
    measurementId: 'G-M43WHJ2EWE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaLqHLf3DiI_YCOYD4O3K7028f_NJ_Km4',
    appId: '1:303738632755:android:24763154312e6f03bb4146',
    messagingSenderId: '303738632755',
    projectId: 'my-flutter-sa-menu',
    storageBucket: 'my-flutter-sa-menu.firebasestorage.app',
  );
}
